spring:
  application:
    name: Database
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:

# spring.datasource.url=
# spring.datasource.username=
# spring.datasource.password=